name: Python package

on: [push, pull_request]

jobs:
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: [3.7]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install and load
      run: |
        pip install .
        python -c "import pv_evaluation"
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Install quarto
      uses: cderv/install-quarto-action@v1
    - name: Test quarto
      run: |
        quarto --version
    - name: Test with pytest
      run: |
        pip install pytest testbook ipykernel jupyter
        pytest