name: Tox

on: [push, pull_request]

jobs:
  build-linux:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        python: [3.7]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Tox
      run: |
        pip install tox
        tox